version: '3'
services:
  lamp:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mattrayner/lamp:latest-1804"
    volumes:
      - ./app:/app
      - ./var_lib_mysql:/var/lib/mysql
    ports:
      - "8080:80"
