version: '3'
services:
  lamp:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mattrayner/lamp:0.8.0-1804-php7"
    volumes:
      - ./app:/app
      - ./var_lib_mysql:/var/lib/mysql
      - ./etc_apache2_sites-enabled/001-todo-spa.conf:/etc/apache2/sites-enabled/001-todo-spa.conf:ro
      - ./etc_apache2_sites-enabled/fullchain.crt:/etc/apache2/sites-enabled/fullchain.crt:ro
      - ./etc_apache2_sites-enabled/privkey.key:/etc/apache2/sites-enabled/privkey.key:ro
    ports:
      - "8080:80"
